# Generated by Django 3.0 on 2023-07-29 21:56

import core.enums
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Uploaded file",
                        upload_to="csv/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ("csv",)
                            )
                        ],
                        verbose_name="file",
                    ),
                ),
            ],
            options={
                "verbose_name": "file",
                "verbose_name_plural": "files",
            },
        ),
        migrations.CreateModel(
            name="Gem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Gem",
                        max_length=core.enums.Limits["GEM_NAME_MAX_CHAR"],
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                core.enums.Regex["GEM_NAME_REGEX"]
                            )
                        ],
                        verbose_name="gem",
                    ),
                ),
            ],
            options={
                "verbose_name": "gem",
                "verbose_name_plural": "gems",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Deal",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total",
                    models.PositiveIntegerField(
                        help_text="The total cost of the deal",
                        verbose_name="total",
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        help_text="Uploaded file",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deals",
                        to="deals.File",
                    ),
                ),
                (
                    "item",
                    models.ManyToManyField(
                        help_text="Deal's gems",
                        related_name="deals",
                        to="deals.Gem",
                        verbose_name="item",
                    ),
                ),
                (
                    "user",
                    models.ManyToManyField(
                        help_text="Customer of the deal",
                        related_name="deals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "deal",
                "verbose_name_plural": "deals",
            },
        ),
    ]
