# Generated by Django 3.0 on 2023-07-29 21:12

import core.enums
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="csv/")),
            ],
        ),
        migrations.CreateModel(
            name="Gem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Gem",
                        max_length=core.enums.Limits["GEM_NAME_MAX_CHAR"],
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                core.enums.Regex["GEM_NAME"]
                            )
                        ],
                        verbose_name="gem",
                    ),
                ),
            ],
            options={
                "verbose_name": "gem",
                "verbose_name_plural": "gems",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Deal",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total",
                    models.PositiveIntegerField(
                        blank=True,
                        default=core.enums.Limits["USER_SPENT_MONEY_VALUE"],
                        help_text="The total cost of the deal",
                        null=True,
                        verbose_name="total",
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deals",
                        to="gems.File",
                    ),
                ),
                (
                    "item",
                    models.ManyToManyField(
                        help_text="Deal stone",
                        related_name="deals",
                        to="gems.Gem",
                        verbose_name="item",
                    ),
                ),
            ],
            options={
                "verbose_name": "deal",
                "verbose_name_plural": "deals",
            },
        ),
    ]
