# Generated by Django 3.0 on 2023-07-29 10:32

import core.enums
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Gem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Gem",
                        max_length=core.enums.Limits["GEM_NAME_MAX_CHAR"],
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                core.enums.Regex["GEM_NAME"]
                            )
                        ],
                        verbose_name="gem",
                    ),
                ),
            ],
            options={
                "verbose_name": "gem",
                "verbose_name_plural": "gems",
                "ordering": ("name",),
            },
        ),
    ]
