# Generated by Django 3.0 on 2023-07-28 14:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("gems", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gem",
            name="user",
            field=models.ManyToManyField(
                help_text="The owner of the gem",
                related_name="gems",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
    ]
